Added TCP LinkLayer to socktap
riebl/vanetza pull request #191
Opened 2023-06-07 22:10 UTC by fysch

I've added TCP to socktap.
To accept incoming connections, use `--tcp-accept 127.0.0.1:12345`.
To connect to another service, use `--tcp-connect 127.0.0.1:12345`.

2023-06-09 18:56 UTC, riebl reviewed
I like the addition of a TCP link layer, this is cool stuff!
Please have a look at my comments which I would like to sort out before merging. Thanks!

2023-06-09 18:56 UTC, riebl commented on tools/socktap/link_layer.cpp
> +    } else if (name.substr(0, 3) == "tcp") {
Why not match the full `name`?

2023-06-09 18:56 UTC, riebl commented on tools/socktap/link_layer.cpp
> +                tcp_ip_len = ip_port.find(":");
I would like to extract the string parsing of IP address and port to a separate function. In this function, we could also do proper error handling. For example, is there a default port if the colon ":" is missing?

2023-06-09 18:56 UTC, riebl commented on tools/socktap/link_layer.cpp
> +        if (vm.count("tcp-connect")) {
I am not sure if `vm.count` is necessary: An empty vector of string would be just fine.

2023-06-09 18:56 UTC, riebl commented on tools/socktap/tcp_link.hpp
> +    std::list<TcpSocket*> sockets_;
using `std::list<TcpSocket>` would eliminate the need for manual memory management with `new` and `delete`

2023-06-09 18:56 UTC, riebl commented on tools/socktap/tcp_link.hpp
> +    std::map<boost::asio::ip::tcp::endpoint, boost::asio::ip::tcp::acceptor*> acceptors_;
Same here, storing `acceptor` objects instead of pointers simplifies memory management.

2023-06-09 18:56 UTC, riebl commented on tools/socktap/tcp_link.cpp
> +#include <boost/asio/ip/multicast.hpp>
You are not using any multicast feature for TCP, are you?

2023-06-09 18:56 UTC, riebl commented on tools/socktap/tcp_link.cpp
> +                    if (callback_) {
You need to check if the callback is set before invoking it: `if (*callback_)`

2023-07-30 18:50 UTC, riebl commented
Nice! Let me give it a final try, I will merge it then.

2023-07-30 21:26 UTC, fysch commented
I've just encountered some issues with it today.
I will try to resolve them in the next days.
So, don't worry about testing right now.

2023-08-05 21:43 UTC, riebl requested changes
I have just noticed that there is no frame delimiter in the TCP stream. Your implementation cannot cope with situations where the IP stack transmits/receives data in chunks of different sizes than your socket calls pass/expect.

2023-08-05 21:43 UTC, riebl commented on tools/socktap/tcp_link.cpp
> +    socket_.write_some(const_buffers, ec);
`write_some` may only transmit the buffers incompletely. I think you should use `write` here.

2023-08-05 21:43 UTC, riebl commented on tools/socktap/tcp_link.cpp
> +    if (!ec) {
TCP streams have no message boundaries by design. Thus, we need to ensure that we take full packets out of the stream. One possibility would be a size field (of fixed size) at the start of each packet. The receiver can read as many bytes as indicated by this field and knows that the next read must be the size field for the follow-up packet.

Example: [uint16: 500] 500 bytes packet [uint16: 400] 400 bytes packet [uint16 ...] ...

2023-08-09 20:23 UTC, riebl commented
Thanks a lot for your patience while contributing your TCP link layer!

2023-08-09 20:23 UTC, merged